apiVersion: v1
kind: Secret
metadata:
  name: genai-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  OPENROUTER_API_KEY: {{ .Values.secrets.OPENROUTER_API_KEY | quote }}
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | quote }}
  LANGSMITH_API_KEY: {{ .Values.secrets.LANGSMITH_API_KEY | quote }}
  MEDICAL_DATA_KEY: {{ .Values.secrets.MEDICAL_DATA_KEY | quote }}
