apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mongo
  ports:
  - name: mongo
    port: {{ .Values.ports.mongo }}
    targetPort: {{ .Values.ports.mongo }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: {{ .Values.namespace }}
spec:
  serviceName: mongo
  replicas: {{ .Values.replicas.mongo }}
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: {{ .Values.images.mongo | quote }}
        ports:
        - containerPort: {{ .Values.ports.mongo }}
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
        readinessProbe:
          tcpSocket:
            port: {{ .Values.ports.mongo }}
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: {{ .Values.ports.mongo }}
          initialDelaySeconds: 20
          periodSeconds: 20
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
