apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: qdrant
  ports:
  - name: http
    port: {{ .Values.ports.qdrantHttp }}
    targetPort: {{ .Values.ports.qdrantHttp }}
  - name: grpc
    port: {{ .Values.ports.qdrantGrpc }}
    targetPort: {{ .Values.ports.qdrantGrpc }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: {{ .Values.namespace }}
spec:
  serviceName: qdrant
  replicas: {{ .Values.replicas.qdrant }}
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
      - name: qdrant
        image: {{ .Values.images.qdrant | quote }}
        ports:
        - containerPort: {{ .Values.ports.qdrantHttp }}
        - containerPort: {{ .Values.ports.qdrantGrpc }}
        volumeMounts:
        - name: qdrant-storage
          mountPath: /qdrant/storage
        readinessProbe:
          tcpSocket:
            port: {{ .Values.ports.qdrantHttp }}
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: {{ .Values.ports.qdrantHttp }}
          initialDelaySeconds: 20
          periodSeconds: 20
      volumes:
      - name: qdrant-storage
        persistentVolumeClaim:
          claimName: qdrant-pvc
