version: 1
formatters:
  default:
    format: '%(asctime)s | %(levelname)s | trace_id=%(otelTraceID)s | span_id=%(otelSpanID)s | %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
loggers:
  uvicorn:
    handlers: [console]
    level: INFO
    propagate: False
  uvicorn.access:
    handlers: [console]
    level: INFO
    propagate: False
  uvicorn.error:
    handlers: [console]
    level: INFO
    propagate: False
root:
  handlers: [console]
  level: INFO
