apiVersion: v1
kind: ConfigMap
metadata:
  name: genai-config
  namespace: genai
data:
  CHAT_SERVICE_URL: http://chat-service:8003
  USER_SERVICE_URL: http://user-service:8001
  PRODUCT_SERVICE_URL: http://product-service:8082
  MONGO_URI: mongodb://mongo:27017
  MONGO_DB: genai_med
  QDRANT_URL: http://qdrant:6333
  AI_SERVICE_URL: http://ai-service:8004
  VITE_API_BASE_URL: http://gateway:8000
  OPENROUTER_API_BASE_URL: https://openrouter.ai/api
  LANGFUSE_BASE_URL: http://langfuse:3000
  LANGFUSE_HOST: http://langfuse:3000
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://tempo:4318/v1/traces
  OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
